# Generated by Django 5.0.2 on 2024-02-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charcode', models.CharField(max_length=3)),
                ('rate', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
